dashboard:
  mailmanagment:
    label: Mail
    uri:
    class: envelope
    order: 98
    pages:
      edit:
        label: All Templates
        module: mail
        controller: management
        action: index
        route: default
      send:
        label: Send Mail
        module: mail
        controller: management
        action: send
        route: default